development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PROD_DB_NAME'] %>
  username: <%= ENV['PROD_DB_USER'] %>
  password: <%= ENV['PROD_DB_PASS'] %>
  host: <%= ENV['PROD_DB_HOST'] %>